[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "langgraph-core"
dynamic = ["version"]
description = "Core langgraph functionality"
dependencies = [
    "agent-core"
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../.."

[tool.hatch.build.targets.wheel]
packages = ["src/agent_core/langgraph_core"]

[tool.uv.sources]
agent-core = { workspace = true }
