[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "oai-langgraph-core"
dynamic = ["version"]
description = "Shim for langgraph-core"
dependencies = [
    "langgraph-core"
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../.."

[tool.hatch.build.targets.wheel]
packages = ["src/oai_langgraph_core"]

[tool.uv.sources]
langgraph-core = { workspace = true }
